sullo/nikto

program/databases/db_tests
A match of "Authentic" is also matching if the page contains something like "Authentication". According to:
http://www.net-security.org/vuln.php?id=2754
the syntax for this pattern is "Authentic=0" so just testing against "Authentic=" to avoid this.
=> Fix FP in Nuca Webserver test

program/plugins/nikto_core.plugin
Only basic checks, closes #207 
This could be also extended to check for stuff like:
@CGIDIRS/foo
@CGIDIRS//foo
foo//bar
=> Added basic check for double slashes in db_tests

program/databases/db_tests
See: http://carnal0wnage.attackresearch.com/2015/02/cisco-asa-version-grabber-cve-2014-3398.html
=> Added check for Cisco ASA info leak

program/databases/db_outdated, program/databases/db_server_msgs
Currently only an banner based test. If its possible to send an non-valid ASCII char (See [1]) in the Referer: header of Nikto i could also do an active check.
[1] http://blog.gdssecurity.com/labs/2015/2/25/jetleak-vulnerability-remote-leakage-of-shared-buffers-in-je.html
=> Added version check for Jetleak (2015-2080)

program/databases/db_content_search
Could detect string like:
```
PDOException: SQLSTATE[HY000] [1044] Access denied for user 'user'@'%' to database 'db' in lock_may_be_available() (line 167 of /var/www/htdocs/includes/lock.inc).
```
which exposes the database user and database name.
=> Add database error string to general content matching

program/databases/db_headers, program/plugins/nikto_headers.plugin
This header contains the version number of Google's [PageSpeed Module](https://developers.google.com/speed/pagespeed/module), and it's
- recognized as an uncommon header and
- the version number is falsely recognized as an IP address.
Here's an example:
+ IP address found in the 'x-mod-pagespeed' header. The IP is "1.7.30.4".
+ Uncommon header 'x-mod-pagespeed' found, with contents: 1.7.30.4-3847
This patch solves these problems one commit at a time. Note: `nikto_headers.plugin` had only one non-whitespace line addition, use `-w` along with `git show` or `git diff` to ignore the indentation fixup.
=> Added header X-Mod-Pagespeed

program/databases/db_outdated
Also removed PHP 5.3 as this branch has reached EOL in August 2014:
https://php.net/eol.php
=> Update PHP versions (fixes #252)

program/plugins/nikto_core.plugin
The check could have catched: https://github.com/sullo/nikto/pull/257
Not quite sure about the 003348 and 003349 tests so i'm excluding them for now.
Also changed tabs to spaces in the other two checks and fixed the indent.
=> Add --dbcheck for wrong used slash after @VARIABLE

program/databases/db_tests
/docs/html/index.html is because of a buggy package in Debian Jessie which places the documentation there and not in /doc/html/index.html.
=> Added documentation location for newer phpMyAdmin versions

program/databases/db_tests, program/databases/db_variables
Ref: https://www.trustwave.com/Resources/SpiderLabs-Blog/Zero-day-in-Magmi-database-client-for-popular-e-commerce-platform-Magento-targeted-in-the-wild/
Also added the older LFI from https://www.exploit-db.com/exploits/35996/. Unfortunately the local.xml won't work here.
=> Added checks for MAGMI LFIs and identification of MAGMI itself

program/databases/db_tests
Minor addition to prevent false positives.
Ektron returns a XML file, e.g.
```
<installation>
<CMS400 DATE=01-01-2001">1.22</CMS400>
<CMS400 DATE="01-01-2013">1.23</CMS400>
</installation>
```
=> Refined check for Ektron CMS version

program/templates/xml_end.tmpl, program/templates/xml_start.tmpl
The existing XML output template does not unmarshall successfully due to orphan <niktoscan> XML tags. The current output format is similar to the following:
```
<niktoscan>
<scandetails>
</scandetails>
<niktoscan>
<scandetails>
</scandetails>
</niktoscan>
```
I have updated the template to include a top order <niktoscan> XML tag and then to close out the sub niktoscan tag preceeding each completed scandetails section. the update would output the following format:
```
<niktoscan>
<niktoscan>
<scandetails>
</scandetails>
</niktoscan
<niktoscan>
<scandetails>
</scandetails>
</niktoscan>
</niktoscan>
```
This will unmarshall successfully.
=> Update XML output template format

program/databases/db_favicon, program/plugins/nikto_core.plugin
Sorry, had broken this in https://github.com/sullo/nikto/pull/305. I wasn't aware that the first header/column is actually needed.
To avoid having an false positive within the --dbcheck the line in nikto_core.plugin is needed.
=> Fix header in db_favicon.

program/databases/db_tests
Ref: https://www.exploit-db.com/exploits/39184/
Vuln devices can be found via: https://www.shodan.io/search?query=%22Embedded+HTTP+Server%22
Also just removed the mab.nfs test, this was just a typo and already exists within the db_domino.
=> Added cisco http firewall lfi test

program/databases/db_tests, program/databases/db_variables
Examples:
http://modpagespeed.com/mod_pagespeed_statistics
http://modpagespeed.com/mod_pagespeed_global_statistics
http://modpagespeed.com/mod_pagespeed_message
http://modpagespeed.com/pagespeed_admin/
http://modpagespeed.com/pagespeed_global_admin/
=> Added check for PageSpeed Module Admin Pages.

program/plugins/nikto_dir_traversal.plugin
Part of https://github.com/sullo/nikto/issues/338
Also fixed a FP in the regex for the boot.ini
There is currently only one issue i can't solve:
When using ``@TRAVLIN`` or ``@TRAVALL`` in db_dir_traversal everything works fine. But as soon as i'm using ``@TRAVWIN`` the ``if ($uri =~ "\@TRAVWIN") {`` doesn't "kick in".
=> Deduplicate code in nikto_dir_traversal.plugin

program/databases/db_multiple_index, program/plugins/nikto_dir_traversal.plugin
Some IDS detect 'etc/passwd' request and block.
So added 'etc/hosts' file check.
Because of historical reasons, some administrators register php4, php5 extensions.
=> Added 'etc/hosts' check and some php file extensions.

program/databases/db_favicon
**1. Ghost blog favicon**
Ghost blog favicon was updated about 3 yrs ago.
[GitHub history of Ghost blog favicon](https://github.com/TryGhost/Ghost/commits/8808674bbddca93e57d849ddb0a12700571bcd8a/core/shared/favicon.ico)
**2. Kodi Media Center favicon**
Kodi Media Center favicon was updated about 2 yrs ago.
[GitHub history of Kodi Media Center favicon](https://github.com/xbmc/xbmc/commits/f303c86db9a8bb11dd27983dca64235ad3f95a55/addons/webinterface.default/favicon.ico)
**3. PAW Server for Android favicon**
=> Add Ghost, Kodi, PAW server favicon

program/databases/db_headers, program/plugins/nikto_headers.plugin
ngx_pagespeed for nginx has:
X-Page-Speed: 1.10.33.2-7600
instead of:
X-Mod-Pagespeed: 1.10.33.2-7600
in mod_pagespeed
=> Add ngx_pagespeed headers

program/databases/db_tests
As the title says, it adds a check for the PHP Composer composer.json and composer.lock files (https://getcomposer.org/).
Tested using a real world example.
=> Add PHP composer config files

program/databases/db_tests
Double quoted 'require' in the composer checks. Tested locally against one example and works. Should reduce FPs.
=> Improve composer checks

program/databases/db_tests
Follow up of https://github.com/sullo/nikto/commit/d6be53bc9306fef695b5abfa5d2896ad7f6b10b1 with the new location of the Drupal CHANGELOG.txt (previously it was located in "/").
=> Added Drupal CHANGELOG.txt for 8.x

program/plugins/nikto_subdomain.plugin
Running nikto with `-Pl @@ALL` option cause requests to wrong subdomain because nikto_subdomain plugin changes shared data.
=> Fix unintended change of data in nikto_subdomain plugin

program/plugins/nikto_headers.plugin
In case of [WebSEAL](https://stackoverflow.com/tags/webseal/info) servers, the `Server` header contains the version number, which happens to contain four single-digit parts, resulting in the followin lines being printed during a scan.
+ Server: WebSEAL/8.0.1.3
+ IP address found in the 'server' header. The IP is "8.0.1.3".
This patch ignores `Server` headers that start with `WebSEAL/` when looking for IP addresses.
=> WebSEAL version numbers are not IP addresses

program/plugins/nikto_sitefiles.plugin
I'm not sure whether it is good or not to add this feature.
Because:
Alzip is a very famous archive program in *JUST* South Korea, and some sysadmins upload site source files zipped with it.
Is it worth to sacrifice the running speed for the security of small numbers of people?
=> Add Alzip archive extensions

program/plugins/nikto_sitefiles.plugin
Some sysadmins make a mistake when they set J2EE servers up, so site main war file is exposed to the world.
With this pattern, we can detect it.
=> Add .war extensions

program/plugins/nikto_core.plugin
Because of the split on the equals sign, only the value before the first `=` is
used. For example, if you have USERAGENT=aaa=bbb, the useragent should be set
to aaa=bbb and only the first `=` should be used for the split.
=> Support `=` in options

program/plugins/nikto_headers.plugin
From my understanding a ```max-age=0``` value on a HSTS header will disable HSTS.
According to the RFC ```A max-age value of zero (i.e., "max-age=0") signals the UA to cease regarding the host as a Known HSTS Host``` https://tools.ietf.org/html/rfc6797
My Perl is very rusty so you may want to pay close attention to the code I implemented.
=> Add HSTS max-age=0 detection

program/databases/db_tests
This PR adds a match for InnovaStudio file uploader in ASP to `db_test`:
`"007161","0","0","/Editor/assetmanager/assetmanager.asp","GET","Upload\sFile","","","","","InnovaStudio file uploader found","",""`
This complements the existing match for the PHP uploader:
`"006957","0","0","/Editor/assetmanager/assetmanager.php","GET","Upload\sFile","","","","","InnovaStudio file uploader found","",""`
Both the PHP and ASP versions be leveraged to gain code execution.
=> Add match for InnovaStudio file uploader (ASP)

program/plugins/nikto_headers.plugin
I've been meaning to fix this since the 64 bit inode calculations commit. This resolves issue #469
=> Changed ETag logic to only display issue if ETag has inode present

program/docs/nikto.1
Almost no man pages specify the path to the binary, since it's arbitrary where most programs execute from.
=> Remove hard-coded path in man page

program/plugins/nikto_sitefiles.plugin
We did some research for this file being exposed, which we will be releasing a blog post about soon. 
> Out of the 852,301 (85%) of sites that we were able to check, we identified that 736 (0.086%) of them were exposing their database export files publicly with the same name as their domain. This may not seem like a lot, but when you consider the impact of the database contents being exposed to malicious actors, it is a considerable risk to the affected individual sites, and their users.
=> Check for .sql file

program/plugins/nikto_headers.plugin
In case of GlassFish servers, the `x-powered-by` header contains the version number, which happens to contain four single-digit parts, resulting in the following lines being printed during a scan.
+ Retrieved x-powered-by header: Servlet/3.0 JSP/2.2 (Oracle GlassFish Server 3.1.2.2 Java/Oracle Corporation/1.7)
+ IP address found in the 'x-powered-by' header. The IP is "3.1.2.2".
This patch ignores `x-powered-by` headers that contain a GlassFish server banner when looking for IP addresses.
=> GlassFish version numbers are not IP addresses

Dockerfile
https://github.com/sullo/nikto/pull/551 has shown the following:
> - ***** SSL support not available (see docs for SSL install) *****
Adding perl-net-ssleay like shown in the requirements on https://cirt.net/nikto2-docs/installation.html#id2743216 should bring SSL support into the docker installation.
=> Install perl-net-ssleay for SSL support

program/plugins/nikto_headers.plugin
controls for Expect-CT header
- checks whether it exists
- if it exists, checks if it is enforced
=> added support for Expect-CT

program/databases/db_tests
If .gitignore and .hgignore are published, there is a possibility that you can grasp the directory structure.
In that case, the location of the credential file may be identified and exploited.
Ignorefile often indicates the location of the credential file and I think that detection is necessary.
=> add ignore file detection

program/databases/db_tests
OpenID Connect(OIDC) and OAuth 2.0 have [Well-Known URIs](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) for configuration metadata in json format.
New tests:
- `/.well-known/openid-configuration`
- `/.well-known/oauth-authorization-server`
Documentation:
[OIDC](https://openid.net/specs/openid-connect-discovery-1_0.html#WellKnownContents)
[OAuth 2.0](https://tools.ietf.org/html/rfc8414#section-7.3.1)
=> Add tests for openid connect and oauth 2 configuration metadata

Dockerfile
The PR removes git from dependencies and copy the project directly inside the image instead of cloning the project again. What do you think @PaulSec?
=> Use COPY instead of clone the repo

program/databases/db_variables
Right now
`@WORDPRESS=/ /wordpress`
will expand, for example,
`@WORDPRESSwp-login.php`
into
`/wp-login.php`
`/wordpresswp-login.php`
access.log evidence:
=> db_variables: Fix @WORDPRESS variable expansion

program/plugins/nikto_report_json.plugin
This PR should fix the json reporting output and closes #599 
There are few issues with the current reporting as shown in #599:
1- Extra comma after square brackets which used in `vulnerabilities`
2- Extra comma at the end of the last json item.
3- Extra curly brace in case the host is not available like this:
```
{"id": "000029","url":"/","msg":"No web server found on localhost:8000"},}
```
- For the first point i managed to fix it by removing the extra comma which comes after the square bracket.
- For the second and third points i still trying to figure out how should i fix them, My thoughts are reading the content before appending `}\n` in `json_close` so i can either remove the extra comma or change `}\n` to `\n` in case there is no curly brace at the beginning but i still don't know …
=> fix JSON reporting

program/databases/db_tests
Looks like there is a small typo in the test for Symfony Profiler.
[Silex profiler](https://github.com/silexphp/Silex-WebProfiler/blob/master/WebProfilerServiceProvider.php#L68) (which is really just the Symfony Profiler)
=> Fix Symfony Profiler test

program/databases/db_tests
This makes it consistent with the other Match 1 / Fail 1 / Fail 2 all having a space between the text and the number.
=> Fix missing space in field order example.

program/plugins/nikto_report_json.plugin
The Nikto JSON Output is currently still a bit broken.
Related to #601 and #599
Currently the all entries in the vulnerabilities array have a `,` after them, even the last one, which makes it incompatible with the JSON standard and most parsers.
This PR should fix this, by prepending the `,` to all entries in the vulnerabilities array, except the last one.
=> Fixed Syntax Error in the Nikto JSON Format

program/plugins/nikto_core.plugin
Found via -dbcheck:
```
Checking plugins for duplicate test IDs
+ ERROR: Duplicate Test ID: 999961
```
which was introduced in deaaa66b0f86ca6c2f4d3123c5b8c6e920df9efe
=> Fix usage of duplicated IDs.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/false_positive_negative_report.md
Info about this can be found here:
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
Could help to get the info for issues like https://github.com/sullo/nikto/issues/652 directly without having to ask for more info later.
=> Add issue templates for bugs and false positive / negative reports.

.github/ISSUE_TEMPLATE/bug_report.md
Minor improvement for 9d496bddb82ede3245a022bb387cecf9426d080e because `#` are header definitions in markdown and the note doesn't look that nice as headers: #683
=> Update bug_report.md template.

program/databases/db_tests
Hey!
I have added an additional check into db_tests. The check is for JAMon - Java Application Monitor Admin interface which in some cases may be exposed on webservers. More information: http://jamonapi.sourceforge.net
Thanks for the tool and for keeping it alive!
=> Added JAMonAdmin.jsp check

program/nikto.pl
HI,
I realize that there's a line with the word "ERROR" before but to make better clear that there was a scanning problem I suggest to emphasize that in caps:
```
+ ERROR: Error limit (20) reached for host, giving up. Last error: opening stream: can't connect (timeout): Interrupted system call
+ SCAN TERMINATED:  20 error(s) and 4 item(s) reported on remote host
+ End Time:           2020-09-14 14:45:35 (GMT2) (406 seconds)
---------------------------------------------------------------------------
```
This was from a scan where I mimicked a server-side blocking I encountered in real life, like with fail2ban which occurred in the middle of a scan.
Cheers, Dirk
=> Make clear that scan was terminated

program/plugins/LW2.pm, program/plugins/nikto_core.plugin
For https://github.com/sullo/nikto/issues/489: adds in behaviour for the following flags:
* `-ipv4`
* `-ipv6`
* `-check6`
PS The `-check6` target host (_ipv6.google.com_) is hardcoded, but perhaps it could be useful to make that user-configurable? e.g. for someone who is onsite and wants to test DNS & connectivity for an internal IPv6 target.
=> GH#489 - plumb in the -ipv4/-ipv6/-check6 flags

program/plugins/nikto_shellshock.plugin
Additional fix required for #749 / 2420e649cd63ab8a1dcfa015c9fa27b7f1f27524 so that the correct CVE is getting flagged.
=> Fix header checks in shellshock plugin

program/plugins/nikto_report_csv.plugin, program/plugins/nikto_report_html.plugin, program/plugins/nikto_report_json.plugin, program/plugins/nikto_report_nbe.plugin, program/plugins/nikto_report_sqlg.plugin, program/plugins/nikto_report_text.plugin, program/plugins/nikto_report_xml.plugin
While building out a tool to automate nikto scans, I discovered the hard way that nikto was appending reports to the existing one. Running the report multiple times means that the output file is different. I believe that a functional approach is more appropriate, the scan should produce the same output file given the certain arguments.
This is the first tool of this type that I've seen with this behavior. It seems more intuitive to me that the report should overwrite the existing one.
=> nikto reports shoud overwrite old file; not append

program/plugins/nikto_report_json.plugin
Remove unnecessary closed bracket like below.
```
$ ./nikto.pl -h 192.168.0.111 -o output.json
- Nikto v2.1.6
---------------------------------------------------------------------------
+ No web server found on 192.168.0.111:80
---------------------------------------------------------------------------
+ 0 host(s) tested
$ cat output.json
{"id": "000029","OSVDB": "0","url":"/","msg":"No web server found on 192.168.0.111:80"}}
```
=> Fix json file format when error occurred

program/plugins/nikto_cookies.plugin
Before this change, if $int was empty there would be two spaces before the word IP.
=> Removing extra space

program/nikto.pl, program/plugins/LW2.pm
- Fixed 4 instances of error messages printing to STDOUT.
- Fixed 3 instance of error conditions exiting 0.
=> Print errors to STDERR, don't exit 0 on error

program/plugins/nikto_report_json.plugin
There are some messages which are not escaped like [here (backslash)](https://github.com/sullo/nikto/blob/master/program/databases/db_tests#L217) in the databases, and an output is sometimes invalid JSON format.
This PR escapes those messages in JSON report plugin.
=> Escape message in JSON output

program/plugins/nikto_report_json.plugin
WIth recent update when json output was selected nikto couldn't run giving error: `Can't locate object method "new" via package "JSON" at /opt/nikto/program/plugins/nikto_report_json.plugin line 102.`
=> Fix nikto json plugin

program/plugins/nikto_core.plugin, program/plugins/nikto_fileops.plugin
Some error messages were prefixed with `+ERROR`, but only `+ ERROR` are detected as error messages and redirected to stderr
=> fix: add space in err msgs for proper autodetecion

Dockerfile
Docker treats every instruction as a layer and cache them. If anything change (for example content of ./program folder) docker rerun `COPY` layer and every layer after it.
Because of this behavior every time something in ./program folder was changed, docker had to rerun `apk add [...]` and other commands.
With current (changed) order only one layer (`COPY` layer) is rerun in case described above.
=> refactor: reorder docker instructions to benefit from caching

program/nikto.pl, program/plugins/nikto_report_json.plugin
- applied AER00 patch https://github.com/sullo/nikto/pull/807
- `encode` function from `JSON:PP` adds own quotes to encoded text. Because of that `"msg"` field was encoded incorrectly (`"msg": ""[some info]""`)
- $uri was never set which resulted in empty value in the report
- in `json_item` commas was blindly added after every item and then removed in `json_host_end` using `seek(...)`. If there were no vulnerabilities found, instead of comma, '[' would be removed.
- if the specified target does not exist, `json_host_start` is not executed, despite that `json_host_end` is. Because of that report ends up with invalid json `]}`
- for some reason `report_host_end` was called before `report_host_start`, thus resulting in weird behavior of json report plugin
- json report was not usable with …
=> fix invalid/inaccurate json report

Dockerfile
Since support for Alpine 3.12 ended like two years ago, I suggest updating the base image in the Dockerfile to the current release Alpine 3.19.
=> Bump Alpine version in Dockerfile
