- program/plugins/nikto_core.plugin
Nothing really grave but still useful to test for this.
> Check for correct tuning types and updated help banner

- program/databases/db_tests
Catched by https://github.com/sullo/nikto/pull/205
> z is not a used tuning type

- program/databases/db_tests
```
Syntax Check: /usr/src/nikto/program/databases/db_tests
+ ERROR: Duplicate Check Syntax (2): @CGIDIRSformmail.pl,GET,Matt\sWright,,,,,,
6902 entries
```
Duplicate test of 000055
> Remove duplicate test

- program/databases/db_variables
Follow-up of: https://github.com/sullo/nikto/pull/217
The two locations are confirmed from:
http://dl.packetstormsecurity.net/1005-advisories/sa39891.txt
http://www.securityfocus.com/archive/1/515494/30/0/threaded
Also fixed a wrong variable i've committed in the last PR.
> Add some more common axis2 locations

- program/databases/db_tests
> Add check for Adobe BlazeDS

- program/databases/db_variables
Follow-up of: https://github.com/sullo/nikto/pull/217
Source: https://spl0it.wordpress.com/2010/11/23/axis2-deployer-metasploit-modules-upload-exec-via-soap/
> Add another axis2 location

- program/databases/db_tests
Moved this test out of https://github.com/sullo/nikto/pull/231
> Detection of old axis2 login

- program/databases/db_tests
Sorry, picked the wrong file. The index.jsp is just a 302 to the login.jsp
> Use the correct tomcat admin page

- program/databases/db_tests
Drupal 7.30 and 7.31 are also vulnerable. Ref: https://www.drupal.org/SA-CORE-2014-005
> Fix drupal test to detect versions up to 7.31

- program/plugins/nikto_shellshock.plugin
Ref: https://github.com/sullo/nikto/issues/197
I'm a Perl beginner so hopefully the implementation is ok in this way.
Successfully tested against two systems:
Debian Lenny (Vuln against CVE-2014-6271)
Debian Wheezy (Vuln against CVE-2014-6271 and CVE-2014-6278)
> Add CVE-2014-6278 pattern to shellshock plugin

- program/databases/db_tests
URL changed to https://owncloud.org/security/advisories/
> Fix link to ownCloud security advisories

- program/databases/db_tests
status.php output has changed slightly in oC 8.1. All other checks are still working.
> Update status.php check for ownCloud 8.1

- program/plugins/nikto_core.plugin
Those tests needs and GET together with the data in the body according to:
http://news.netcraft.com/archives/2003/01/01/security_advisory_2001111_jrun_ssi_request_body_parsing.html
Also fixed the indent.
> Ignoring three tests in POST data without POST method check

- program/databases/db_outdated
7.0 was the latest stable: https://web.archive.org/web/20080515164944/http://www.sambar.com/download.htm
> Updated Sambar version in db_outdated

- program/databases/db_tests
- program/databases/db_variables
Content only contains a string like:
2014-09-29b "Hrun"
or
2011-05-25a "Rincewind"
> Add check for Dokuwiki VERSION file

- program/databases/db_tests
- program/databases/db_variables
> Revert "Add check for Dokuwiki VERSION file"

- program/databases/db_multiple_index
> Added index.jsp

- program/databases/db_tests
One + too much.
Seems also that --dbcheck is complaining if there is no OSVDB entry.
> Fix last tests

- program/databases/db_tests
```
Syntax Check: /usr/src/nikto/program/databases/db_tests
+ ERROR: Duplicate Check Syntax (2): @VBULLETINfaq.php?s=&do=search&q=database&match=all&titlesonly=0,GET,Database<\/span> Name:,,,,,,
6966 entries
```
> Remove duplicate test.

- program/plugins/nikto_core.plugin
Makes it easier to update the db_favicon.
> Added dbcheck for duplicated db_favicon md5s

- program/databases/db_realms
- program/databases/db_tests
Source: https://github.com/comfy/comfortable-mexican-sofa/wiki/Installation-and-Quick-Start-Guide#quick-start-guide
> Added comfy CMS default credentials

- program/databases/db_tests
- program/plugins/nikto_headers.plugin
> Identify OWA and its version.

- program/plugins/nikto_core.plugin
Only the dbcheck for db_drupal of #313
> Added dbcheck for db_drupal

- program/plugins/nikto_headers.plugin
Fixes #307 and closes #174 
Also changed the text of the test before slightly. This is not affecting only IIS but also many other webservers, load balancers and proxies.
> Check for WWW-Authenticate in nikto headers plugin.

- program/plugins/nikto_domino.plugin
The four checked files might contain different versions.
> nikto_domino plugin: Get highest version, not only the first.

- program/plugins/nikto_domino.plugin
Should also help in reducing FPs. Will see if i can extend the content pattern the next time i'm getting a hand on a Domino Server.
> nikto_domino: Avoid false positive in detection.

- program/databases/db_dir_traversal
- program/plugins/nikto_dir_traversal.plugin
First proposal to fix https://github.com/sullo/nikto/issues/201
Further improvements could be:
- Support POST and GET
- Support directories (like ``@TYPO3``) from db_variables
- Also check for ``($res eq "200") && !(is_404($item->{'file'}, $content, $res, $response->{'location'}))`` ?
- Anything else?
> New directory traversal plugin.

- program/databases/db_tests
Same as https://github.com/sullo/nikto/commit/64bb0f8f134265895edc2c9f3b8577a54df5450e for /server-info
> Incorrect /server-info

- program/plugins/nikto_dir_traversal.plugin
That solved the issue i had in https://github.com/sullo/nikto/pull/339
Also changed the full_name of the plugin.
> nikto_dir_traversal: Move traversal pattern to load sub

- program/databases/db_variables
Follow-up of https://github.com/sullo/nikto/pull/346
Don't know how that mistake happened. :-/
> Make symphony dir lowercase

- program/plugins/nikto_core.plugin
- program/plugins/nikto_report_json.plugin
lazy csv report modified to json, added nikto-id
> added JSON format

- program/databases/db_multiple_index
Follow-up of https://github.com/sullo/nikto/pull/352 for PHP 7
> Add index.php7

- program/databases/db_variables
> Added additional CKEditor dirs

- program/databases/db_tests
This PR adds 2 interesting files to the database
> add sql files

- program/databases/db_tests
Contains something like:
```
phpMyAdmin - Readme
===================
Version 4.0.8
```
including the version of PMA.
> Added check for phpMyAdmin README containing the version

- program/plugins/nikto_domino.plugin
- Gather version from three additional files
- Strip trailing spaces
- Change tabs to spaces
- Fix missing ``/`` in Domino login page
> Nikto Domino Plugin: Updated version detection

- program/plugins/nikto_domino.plugin
Updated detection and some minor stuff. As we saved a lot of requests by moving the .nsf checks into the db_domino we can spent some more requests here.
Also fixed the banner regex as it havn't catched a banner like ``Lotus Domino``
> Update IBM/Lotus Domino detection

- program/databases/db_tests
See https://github.com/LibreOffice/online/blob/1.9.0/loleaflet/README#L93-L107
No default username/password to check.
> Added LibreOffice Online admin interface

- documentation/nikto.1
Hi, I have packaged nikto 2.1.5 in pkgsrc (for NetBSD notably). I have amended the manual page as seen here.
Cheers!
> Slightly improve the manual page

- program/plugins/nikto_strutshock.plugin
I'll improve this plugin later. ;-)
> Add Apache Struts2 RCE (CVE-2017-5638) check

- program/databases/db_tests
* SNMP based device management
* Java applet
* Default community string is public
* You'll need JRE6
> Add Avaya G450/G350 device management web console check

- .editorconfig
- program/databases/db_tests
BTW, can I add the server response header to 'Match1 And' ?
For example, 
"Server: PST10 WebServer"
> Add Miele Professional PG 8528 directory traversal check

- program/plugins/nikto_core.plugin
> Syntax Check: program/databases/db_tests
+ ERROR: Possible incorrect slashes: "007152","0","5","//WEB-INF/web.xml","GET","j2ee","","","","","A web.xml file was retrieved from the WEB-INF directory by prepending an additional slash.","",""
+ If two or more slashes are needed for this test: Please add the ID 007152 at line 1389 in the nikto_core.plugin.
> Resolve double slash error report

- program/databases/db_tests
This pull request modifies db_tests to include checks for the existence of a common ASP.NET component library and a critical vulnerability in the same.  Checks for the library with both a default URI and the URI as used in DNN (a.k.a. DotNetNuke).
> Tests for CVE-2017-9248

- program/plugins/nikto_headers.plugin
> Dirty hack to deal with multiple identical headers being set

- program/databases/db_headers
See https://scotthelme.co.uk/a-new-security-header-expect-ct/
> Added Expect-CT header

- program/plugins/nikto_core.plugin
- program/plugins/nikto_tests.plugin
Example for multiple headers:  
"Authorization: Basic dXNlcjpwYXNzd29yZA==\r\nSOAPAction: Authorized"
> nikto_tests.plugin: Allow tests to specify multiple headers / Set content-length

- program/plugins/nikto_httpoptions.plugin
This URL is not pointing to any valuable content anymore.
> Remove invalid URL for IIS DEBUG test

- README.md
Docker related documentation was missing.
> Add instructions for Docker container usage

- README.md
Correct one as built is sullo/nikto
> Fixed image name we use

- .gitignore
> ignore  nikto.conf  file

- Dockerfile
- Removed the 'make' command from the list of installed packages.
- The COPY instruction only copy the 'program' folder. This reduce the size of the final image from 55.8MB to 47.3MB
- Updating the chown command to all the content from nikto/ now belongs to the user and group nikto.
> Small footprint.

- program/databases/db_tests
Resolves #631 
New tests:
- `/apple-app-site-association`
- `/.well-known/apple-app-site-association`
- `/.well-known/assetlinks.json`
Documentation:
- [Universal Links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html)
- [Android App Links](https://developer.android.com/training/app-links/verify-site-associations.html)
> Add tests for Apple Universal Links and Android App Links

- .gitattributes
Ensure LF line endings. Fix #615
> Fix Docker image build on Windows

- program/nikto.pl
- program/plugins/nikto_core.plugin
- program/replay.pl
Exit with code 1 if errors or vulnerabilites are found
> Exit with code 1

- COPYING
- README.md
Source: https://github.com/sullo/nikto/blob/master/program/nikto.pl#L10
SPDX: GPL-2.0-only
> Clarify licensing terms

- program/databases/db_outdated
- program/databases/db_tests
339fbe2414a8c607caf2a7985ec5c2c36f582822 should have been added to the db_tests.
Login page can be found via e.g. https://www.shodan.io/search?query=title%3A%22BIG-IP%26reg%3B-+Redirect%22
> BIG-IP updates.

- .dockerignore
- Dockerfile
* update alpine to 3.12 and drop the patch version
* use "Installing for" instead of "Selecting to" for packages
* use --update flag of apk
* remove clean cache command as it's already empty with --no-cache flag
* align nikto user creation message with the group
* remove the root password locking stuff: irrelevant with alpine 3.12
* add a .dockerignore file to send less context to the daemon
* bring the image size down from 47.2MB to 45.7MB
> Improve the docker image build

- program/nikto.pl
.. so that calling scripts also realize that didn't work
> Setting proper exit code when scan was terminated

- .github/ISSUE_TEMPLATE/FeatureRequest.md
- documentation/nikto.1
- program/databases/db_404_strings
- program/databases/db_content_search
- program/databases/db_dictionary
- program/databases/db_domino
- program/databases/db_drupal
- program/databases/db_embedded
- program/databases/db_favicon
- program/databases/db_headers
- program/databases/db_httpoptions
- program/databases/db_multiple_index
- program/databases/db_outdated
- program/databases/db_parked_strings
- program/databases/db_realms
- program/databases/db_server_msgs
- program/databases/db_tests
- program/databases/db_variables
- program/docs/nikto.1
- program/plugins/LW2.pm
- program/plugins/nikto_core.plugin
- program/plugins/nikto_httpoptions.plugin
- program/plugins/nikto_ms10_070.plugin
- program/plugins/nikto_msgs.plugin
> Typos found by codespell

- program/plugins/nikto_cookies.plugin
Decodes netscaler cookie to find server ip.
https://cybernomad.online/2012/01/03/netscaler-making-sense-of-the-cookie-part-1/
> detect ip from netscaler cookie

- .gitignore
- program/plugins/nikto_cookies.plugin
same update for 2.5.0 branch
https://github.com/sullo/nikto/pull/748
> decode netscaler cookie

- Dockerfile
Update base alpine image version from 3.12 to 3.15 in Dockerfile
Tested locally with created `scorpio2002/nikto:3.15` image, all looks fine
> Bump alpine to 3.15 version

- program/databases/db_tests
Add the file signature (first 4 bytes) for /.git/index
ref: https://git-scm.com/docs/index-format
> Add file signature for /.git/index

- program/databases/db_headers
fixes https://github.com/sullo/nikto/issues/813
> Don't report the traceparent header

- Dockerfile
Upgrade alpine version from 3.19 to 3.2
> fix: Upgrade alpine version from 3.19 to 3.2

- program/databases/db_outdated
Got broken in 26375319a13f76d3ae16ab35d51bfb662ecd24b7 for unknown reasons, just fixing it.
> Wrong Apache version in db_outdated
